### ISSUE TITLE
Undefined symbol PyList_New

### ISSUE THREAD

**Issue by durian** [pbuckner/x-plane_plugins#3]
I compiled the plugin on Arch Linux, and installed it into X-Plabe 11.50b11. I get the following in the log:
Fetching plugins for /a/X-Plane11.50b/Resources/plugins
Loaded: /a/X-Plane11.50b/Resources/plugins/PluginAdmin/64/lin.xpl (xpsdk.examples.pluginadmin).
dlerror:/a/X-Plane11.50b/Resources/plugins/XPPython3/lin_x64/XPPython3.xpl: undefined symbol: PyList_New

I compiled the plugin myself, didn't get any errors.

uname -a:
Linux margretetorp 5.7.4-arch1-1 #1 SMP PREEMPT Thu, 18 Jun 2020 16:01:07 +0000 x86_64 GNU/Linux

[Log.txt](https://github.com/pbuckner/x-plane_plugins/files/4809670/Log.txt)

**Comment by pbuckner** [comment]
PyList_New is defined in the python library, so I guess that's not being found by XPlane on startup? (You should be able to use the provided xpl, rather than building your own -- by I have no reason to think that is the cause of your issue.)

I don't have a linux machine with sufficient graphics to run X-Plane, so I cannot give more definite info at this time.

**Comment by durian** [comment]
The original is linked with libpython3.6m.so.1.0, which I don't have, therefor I tried to compile it myself. Might have done something wrong... I will close this for now, and investigate. Thanks for making a new Python plugin!

**Comment by pbuckner** [comment]
Got it: it should be linked against a minimal Python API (3.3/3.5, I think). I’ll check think linker instructions: likely my fault. 

--
Peter
